<@php

namespace {namespace};

use {useStatement};
use CodeIgniter\Shield\Models\UserModel;

/**
 * CRUD controller for Shield users.
 * Generated by: php spark module:create {directoryName} --crud
 */
class {class} extends {extends}
{
    protected $folder_directory = "Modules\\{directoryName}\\Views\\";
    protected UserModel $userModel;
    protected $data = [];

    public function __construct()
    {
        $this->userModel = new UserModel();
    }

    // -------------------------------------------------------------------------
    // List all users (DataTables)
    // -------------------------------------------------------------------------

    public function index()
    {
        if (!user_id()) {
            return redirect()->route('login');
        }

        $this->data['page_title']    = '{directoryName} - Users';
        $this->data['page_header']   = 'Users';
        $this->data['is_datatables'] = true;
        $this->data['contents']      = [$this->folder_directory . 'index'];

        $this->data['users'] = $this->userModel
            ->select('users.id, users.username, users.status, auth_identities.secret AS email, users.created_at')
            ->join('auth_identities', 'auth_identities.user_id = users.id AND auth_identities.type = "email_password"', 'left')
            ->findAll();

        return $this->render();
    }

    // -------------------------------------------------------------------------
    // Create user — show form
    // -------------------------------------------------------------------------

    public function create()
    {
        if (!user_id()) {
            return redirect()->route('login');
        }

        $this->data['page_title']  = '{directoryName} - Create User';
        $this->data['page_header'] = 'Create User';
        $this->data['contents']    = [$this->folder_directory . 'create'];

        return $this->render();
    }

    // -------------------------------------------------------------------------
    // Create user — store
    // -------------------------------------------------------------------------

    public function store()
    {
        if (!user_id()) {
            return redirect()->route('login');
        }

        $rules = [
            'username' => 'required|min_length[3]|max_length[30]|is_unique[users.username]',
            'email'    => 'required|valid_email|is_unique[auth_identities.secret]',
            'password' => 'required|min_length[8]',
        ];

        if (!$this->validate($rules)) {
            return redirect()->back()->withInput()->with('errors', $this->validator->getErrors());
        }

        $users = auth()->getProvider();

        /** @var \CodeIgniter\Shield\Entities\User $user */
        $user = new \CodeIgniter\Shield\Entities\User([
            'username' => $this->request->getPost('username'),
        ]);

        $users->save($user);
        $user = $users->findById($users->getInsertID());

        $user->createEmailIdentity([
            'email'    => $this->request->getPost('email'),
            'password' => $this->request->getPost('password'),
        ]);

        return redirect()->to('/{groupName}')->with('message', 'User created successfully.');
    }

    // -------------------------------------------------------------------------
    // Edit user — show form
    // -------------------------------------------------------------------------

    public function edit(int $id)
    {
        if (!user_id()) {
            return redirect()->route('login');
        }

        $userRow = $this->userModel
            ->select('users.id, users.username, users.status, auth_identities.secret AS email')
            ->join('auth_identities', 'auth_identities.user_id = users.id AND auth_identities.type = "email_password"', 'left')
            ->find($id);

        if ($userRow === null) {
            return redirect()->to('/{groupName}')->with('error', 'User not found.');
        }

        $this->data['page_title']  = '{directoryName} - Edit User';
        $this->data['page_header'] = 'Edit User';
        $this->data['contents']    = [$this->folder_directory . 'edit'];
        $this->data['userRow']     = $userRow;

        return $this->render();
    }

    // -------------------------------------------------------------------------
    // Edit user — update
    // -------------------------------------------------------------------------

    public function update(int $id)
    {
        if (!user_id()) {
            return redirect()->route('login');
        }

        $users   = auth()->getProvider();
        $editUser = $users->findById($id);

        if ($editUser === null) {
            return redirect()->to('/{groupName}')->with('error', 'User not found.');
        }

        $rules = [
            'username' => "required|min_length[3]|max_length[30]|is_unique[users.username,id,{$id}]",
            'email'    => "required|valid_email|is_unique[auth_identities.secret,user_id,{$id}]",
        ];

        $newPassword = $this->request->getPost('new_password');
        if (!empty($newPassword)) {
            $rules['new_password'] = 'min_length[8]';
        }

        if (!$this->validate($rules)) {
            return redirect()->back()->withInput()->with('errors', $this->validator->getErrors());
        }

        // Update username
        $editUser->username = $this->request->getPost('username');
        $users->save($editUser);

        // Update email identity
        $identity = $editUser->getEmailIdentity();
        if ($identity !== null) {
            $identity->secret = $this->request->getPost('email');

            if (!empty($newPassword)) {
                $identity->secret2 = service('passwords')->hash($newPassword);
            }

            $users->saveIdentity($identity);
        }

        return redirect()->to('/{groupName}')->with('message', 'User updated successfully.');
    }

    // -------------------------------------------------------------------------
    // Delete user (soft-delete)
    // -------------------------------------------------------------------------

    public function delete(int $id)
    {
        if (!user_id()) {
            return redirect()->route('login');
        }

        $this->userModel->delete($id);

        return redirect()->to('/{groupName}')->with('message', 'User deleted.');
    }

    /**
     * Renders the admin layout.
     */
    public function render(): string
    {
        return stn_view('index', $this->data);
    }
}
